levels = [{
    "rabbit": {
      "x": 2,
      "y": 15
    },
    "platforms": [{
      "image": "ground-1",
      "x": 0,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 1,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 2,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 3,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 4,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 5,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 6,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 7,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 8,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 9,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 10,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 11,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 12,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 13,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 14,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 15,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 16,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 17,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 18,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 19,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 20,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 1,
      "y": 10
    }, {
      "image": "ground-1",
      "x": 2,
      "y": 10
    }, {
      "image": "ground-1",
      "x": 3,
      "y": 10
    }, {
      "image": "ground-1",
      "x": 4,
      "y": 10
    }, {
      "image": "ground-1",
      "x": 5,
      "y": 10
    }, {
      "image": "ground-1",
      "x": 6,
      "y": 10
    }, {
      "image": "ground-1",
      "x": 7,
      "y": 10
    }, {
      "image": "ground-1",
      "x": 8,
      "y": 10
    }, {
      "image": "ground-2",
      "x": 13,
      "y": 9
    }, {
      "image": "ground-2",
      "x": 14,
      "y": 9
    }, {
      "image": "ground-2",
      "x": 15,
      "y": 9
    }, {
      "image": "ground-2",
      "x": 16,
      "y": 9
    }, {
      "image": "ground-2",
      "x": 17,
      "y": 9
    }, {
      "image": "ground-1",
      "x": 13,
      "y": 8
    }, {
      "image": "ground-1",
      "x": 14,
      "y": 8
    }, {
      "image": "ground-1",
      "x": 15,
      "y": 8
    }, {
      "image": "ground-1",
      "x": 16,
      "y": 8
    }, {
      "image": "ground-1",
      "x": 17,
      "y": 8
    }, {
      "image": "ground-1",
      "x": 4,
      "y": 3
    }, {
      "image": "ground-1",
      "x": 5,
      "y": 3
    }, {
      "image": "ground-1",
      "x": 6,
      "y": 3
    }, {
      "image": "ground-1",
      "x": 7,
      "y": 3
    }, {
      "image": "ground-1",
      "x": 8,
      "y": 3
    }, {
      "image": "ground-1",
      "x": 9,
      "y": 3
    }, {
      "image": "ground-1",
      "x": 10,
      "y": 3
    }, {
      "image": "ground-1",
      "x": 11,
      "y": 3
    }, {
      "image": "ground-1",
      "x": 12,
      "y": 3
    }],
    "ladders": [{
      "x": 3,
      "y": 3
    }, {
      "x": 3,
      "y": 4
    }, {
      "x": 3,
      "y": 5
    }, {
      "x": 3,
      "y": 6
    }, {
      "x": 3,
      "y": 7
    }, {
      "x": 3,
      "y": 8
    }, {
      "x": 3,
      "y": 9
    }, {
      "x": 9,
      "y": 10
    }, {
      "x": 9,
      "y": 11
    }, {
      "x": 9,
      "y": 12
    }, {
      "x": 9,
      "y": 13
    }, {
      "x": 9,
      "y": 14
    }, {
      "x": 9,
      "y": 15
    }],
    "carrots": [{
      "x": 8,
      "y": 2
    }, {
      "x": 13,
      "y": 2
    }, {
      "x": 13,
      "y": 4
    }, {
      "x": 13,
      "y": 6
    }, {
      "x": 6,
      "y": 9
    }, {
      "x": 1,
      "y": 9
    }, {
      "x": 5,
      "y": 15
    }, {
      "x": 15,
      "y": 15
    }],
    "foxes": [{
      "x": 17,
      "y": 7,
      "direction": "left"
    }]
  }, {
    "rabbit": {
      "x": 1,
      "y": 3
    },
    "platforms": [{
      "image": "ground-1",
      "x": 0,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 1,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 2,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 3,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 4,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 5,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 6,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 7,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 8,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 9,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 10,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 11,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 12,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 13,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 14,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 15,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 16,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 17,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 18,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 19,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 20,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 0,
      "y": 9
    }, {
      "image": "ground-1",
      "x": 1,
      "y": 9
    }, {
      "image": "ground-1",
      "x": 2,
      "y": 9
    }, {
      "image": "ground-1",
      "x": 3,
      "y": 9
    }, {
      "image": "ground-1",
      "x": 4,
      "y": 9
    }, {
      "image": "ground-1",
      "x": 5,
      "y": 9
    }, {
      "image": "ground-1",
      "x": 6,
      "y": 9
    }, {
      "image": "ground-1",
      "x": 7,
      "y": 9
    }, {
      "image": "ground-1",
      "x": 8,
      "y": 9
    }, {
      "image": "ground-1",
      "x": 9,
      "y": 9
    }, {
      "image": "ground-1",
      "x": 10,
      "y": 9
    }, {
      "image": "ground-1",
      "x": 11,
      "y": 9
    }, {
      "image": "ground-1",
      "x": 12,
      "y": 9
    }, {
      "image": "ground-1",
      "x": 13,
      "y": 9
    }, {
      "image": "ground-1",
      "x": 0,
      "y": 4
    }, {
      "image": "ground-1",
      "x": 1,
      "y": 4
    }, {
      "image": "ground-1",
      "x": 2,
      "y": 4
    }, {
      "image": "ground-1",
      "x": 3,
      "y": 4
    }, {
      "image": "ground-1",
      "x": 4,
      "y": 4
    }, {
      "image": "ground-1",
      "x": 6,
      "y": 4
    }, {
      "image": "ground-1",
      "x": 7,
      "y": 4
    }],
    "ladders": [{
      "x": 5,
      "y": 4
    }, {
      "x": 5,
      "y": 5
    }, {
      "x": 5,
      "y": 6
    }, {
      "x": 5,
      "y": 7
    }, {
      "x": 5,
      "y": 8
    }, {
      "x": 14,
      "y": 9
    }, {
      "x": 14,
      "y": 10
    }, {
      "x": 14,
      "y": 11
    }, {
      "x": 14,
      "y": 12
    }, {
      "x": 14,
      "y": 13
    }, {
      "x": 14,
      "y": 14
    }, {
      "x": 14,
      "y": 15
    }],
    "carrots": [{
      "x": 7,
      "y": 3
    }, {
      "x": 4,
      "y": 8
    }, {
      "x": 13,
      "y": 8
    }, {
      "x": 19,
      "y": 15
    }, {
      "x": 1,
      "y": 15
    }],
    "foxes": [{
      "x": 0,
      "y": 8,
      "direction": "right"
    }, {
      "x": 12,
      "y": 8,
      "direction": "left"
    }, {
      "x": 5,
      "y": 15,
      "direction": "right"
    }]
  }, {
    "rabbit": {
      "x": 10,
      "y": 1
    },
    "platforms": [{
      "image": "ground-1",
      "x": 0,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 1,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 2,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 3,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 4,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 5,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 6,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 7,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 8,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 9,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 10,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 11,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 12,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 13,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 14,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 15,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 16,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 17,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 18,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 19,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 20,
      "y": 16
    }, {
      "image": "ground-2",
      "x": 6,
      "y": 4
    }, {
      "image": "ground-2",
      "x": 14,
      "y": 4
    }, {
      "image": "ground-2",
      "x": 7,
      "y": 9
    }, {
      "image": "ground-2",
      "x": 13,
      "y": 9
    }],
    "ladders": [{
      "x": 6,
      "y": 3
    }, {
      "x": 7,
      "y": 3
    }, {
      "x": 8,
      "y": 3
    }, {
      "x": 9,
      "y": 3
    }, {
      "x": 10,
      "y": 3
    }, {
      "x": 11,
      "y": 3
    }, {
      "x": 12,
      "y": 3
    }, {
      "x": 13,
      "y": 3
    }, {
      "x": 14,
      "y": 3
    }, {
      "x": 5,
      "y": 4
    }, {
      "x": 15,
      "y": 4
    }, {
      "x": 5,
      "y": 5
    }, {
      "x": 6,
      "y": 5
    }, {
      "x": 7,
      "y": 5
    }, {
      "x": 8,
      "y": 5
    }, {
      "x": 9,
      "y": 5
    }, {
      "x": 10,
      "y": 5
    }, {
      "x": 11,
      "y": 5
    }, {
      "x": 12,
      "y": 5
    }, {
      "x": 13,
      "y": 5
    }, {
      "x": 14,
      "y": 5
    }, {
      "x": 15,
      "y": 5
    }, {
      "x": 6,
      "y": 6
    }, {
      "x": 7,
      "y": 6
    }, {
      "x": 8,
      "y": 6
    }, {
      "x": 12,
      "y": 6
    }, {
      "x": 13,
      "y": 6
    }, {
      "x": 14,
      "y": 6
    }, {
      "x": 6,
      "y": 7
    }, {
      "x": 7,
      "y": 7
    }, {
      "x": 10,
      "y": 7
    }, {
      "x": 13,
      "y": 7
    }, {
      "x": 14,
      "y": 7
    }, {
      "x": 6,
      "y": 8
    }, {
      "x": 7,
      "y": 8
    }, {
      "x": 8,
      "y": 8
    }, {
      "x": 12,
      "y": 8
    }, {
      "x": 13,
      "y": 8
    }, {
      "x": 14,
      "y": 8
    }, {
      "x": 6,
      "y": 9
    }, {
      "x": 7,
      "y": 9
    }, {
      "x": 13,
      "y": 9
    }, {
      "x": 14,
      "y": 9
    }, {
      "x": 6,
      "y": 10
    }, {
      "x": 8,
      "y": 10
    }, {
      "x": 9,
      "y": 10
    }, {
      "x": 10,
      "y": 10
    }, {
      "x": 11,
      "y": 10
    }, {
      "x": 12,
      "y": 10
    }, {
      "x": 13,
      "y": 10
    }, {
      "x": 14,
      "y": 10
    }, {
      "x": 6,
      "y": 11
    }, {
      "x": 8,
      "y": 11
    }, {
      "x": 9,
      "y": 11
    }, {
      "x": 10,
      "y": 11
    }, {
      "x": 11,
      "y": 11
    }, {
      "x": 12,
      "y": 11
    }, {
      "x": 14,
      "y": 11
    }, {
      "x": 6,
      "y": 12
    }, {
      "x": 7,
      "y": 12
    }, {
      "x": 8,
      "y": 12
    }, {
      "x": 9,
      "y": 12
    }, {
      "x": 10,
      "y": 12
    }, {
      "x": 11,
      "y": 12
    }, {
      "x": 12,
      "y": 12
    }, {
      "x": 13,
      "y": 12
    }, {
      "x": 14,
      "y": 12
    }, {
      "x": 6,
      "y": 13
    }, {
      "x": 14,
      "y": 13
    }],
    "carrots": [{
      "x": 7,
      "y": 4
    }, {
      "x": 10,
      "y": 4
    }, {
      "x": 13,
      "y": 4
    }, {
      "x": 8,
      "y": 7
    }, {
      "x": 12,
      "y": 7
    }, {
      "x": 10,
      "y": 8
    }, {
      "x": 10,
      "y": 9
    }, {
      "x": 7,
      "y": 10
    }, {
      "x": 13,
      "y": 11
    }, {
      "x": 10,
      "y": 14
    }],
    "foxes": [{
      "x": 9,
      "y": 4,
      "direction": "left"
    }, {
      "x": 11,
      "y": 9,
      "direction": "left"
    }]
  },
  {
    "rabbit": {
      "x": 1,
      "y": 1
    },
    "platforms": [{
      "image": "ground-1",
      "x": 6,
      "y": 1
    }, {
      "image": "ground-1",
      "x": 7,
      "y": 1
    }, {
      "image": "ground-1",
      "x": 14,
      "y": 1
    }, {
      "image": "ground-1",
      "x": 15,
      "y": 1
    }, {
      "image": "ground-1",
      "x": 16,
      "y": 1
    }, {
      "image": "ground-1",
      "x": 17,
      "y": 1
    }, {
      "image": "ground-1",
      "x": 18,
      "y": 1
    }, {
      "image": "ground-1",
      "x": 19,
      "y": 1
    }, {
      "image": "ground-1",
      "x": 1,
      "y": 2
    }, {
      "image": "ground-1",
      "x": 2,
      "y": 2
    }, {
      "image": "ground-1",
      "x": 3,
      "y": 2
    }, {
      "image": "ground-1",
      "x": 4,
      "y": 2
    }, {
      "image": "ground-2",
      "x": 2,
      "y": 3
    }, {
      "image": "ground-2",
      "x": 3,
      "y": 3
    }, {
      "image": "ground-1",
      "x": 9,
      "y": 4
    }, {
      "image": "ground-1",
      "x": 10,
      "y": 4
    }, {
      "image": "ground-1",
      "x": 15,
      "y": 6
    }, {
      "image": "ground-1",
      "x": 16,
      "y": 6
    }, {
      "image": "ground-1",
      "x": 17,
      "y": 6
    }, {
      "image": "ground-1",
      "x": 18,
      "y": 6
    }, {
      "image": "ground-1",
      "x": 19,
      "y": 6
    }, {
      "image": "ground-1",
      "x": 12,
      "y": 7
    }, {
      "image": "ground-1",
      "x": 13,
      "y": 7
    }, {
      "image": "ground-1",
      "x": 4,
      "y": 9
    }, {
      "image": "ground-1",
      "x": 4,
      "y": 9
    }, {
      "image": "ground-1",
      "x": 5,
      "y": 9
    }, {
      "image": "ground-1",
      "x": 6,
      "y": 9
    }, {
      "image": "ground-1",
      "x": 7,
      "y": 9
    }, {
      "image": "ground-1",
      "x": 8,
      "y": 9
    }, {
      "image": "ground-1",
      "x": 14,
      "y": 11
    }, {
      "image": "ground-1",
      "x": 15,
      "y": 11
    }, {
      "image": "ground-1",
      "x": 16,
      "y": 11
    }, {
      "image": "ground-1",
      "x": 17,
      "y": 11
    }, {
      "image": "ground-1",
      "x": 18,
      "y": 11
    }, {
      "image": "ground-1",
      "x": 19,
      "y": 11
    }, {
      "image": "ground-1",
      "x": 20,
      "y": 11
    }, {
      "image": "ground-1",
      "x": 10,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 11,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 12,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 13,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 14,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 15,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 16,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 17,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 18,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 19,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 20,
      "y": 16
    }],
    "ladders": [{
      "x": 8,
      "y": 1
    }, {
      "x": 8,
      "y": 2
    }, {
      "x": 8,
      "y": 3
    }, {
      "x": 8,
      "y": 4
    }, {
      "x": 11,
      "y": 4
    }, {
      "x": 11,
      "y": 5
    }, {
      "x": 11,
      "y": 6
    }, {
      "x": 11,
      "y": 7
    }, {
      "x": 20,
      "y": 1
    }, {
      "x": 20,
      "y": 2
    }, {
      "x": 20,
      "y": 3
    }, {
      "x": 20,
      "y": 4
    }, {
      "x": 20,
      "y": 5
    }, {
      "x": 20,
      "y": 6
    }, {
      "x": 20,
      "y": 7
    }, {
      "x": 20,
      "y": 8
    }, {
      "x": 20,
      "y": 9
    }, {
      "x": 20,
      "y": 10
    }, {
      "x": 13,
      "y": 11
    }, {
      "x": 13,
      "y": 12
    }, {
      "x": 13,
      "y": 13
    }, {
      "x": 13,
      "y": 14
    }, {
      "x": 13,
      "y": 15
    }, {
      "x": 9,
      "y": 16
    }, {
      "x": 1,
      "y": 14
    }, {
      "x": 1,
      "y": 15
    }, {
      "x": 1,
      "y": 16
    }],
    "carrots": [{
      "x": 6,
      "y": 0
    }, {
      "x": 14,
      "y": 0
    }, {
      "x": 10,
      "y": 3
    }, {
      "x": 15,
      "y": 5
    }, {
      "x": 8,
      "y": 6
    }, {
      "x": 2,
      "y": 9
    }, {
      "x": 12,
      "y": 15
    }],
    "foxes": [{
      "x": 5,
      "y": 8,
      "direction": "left"
    }, {
      "x": 15,
      "y": 10,
      "direction": "right"
    }, {
      "x": 17,
      "y": 15,
      "direction": "right"
    }, {
      "x": 9,
      "y": 16,
      "direction": "left"
    }]
  },
  {
    "rabbit": {
      "x": 9,
      "y": 2
    },
    "platforms": [{
      "image": "ground-1",
      "x": 14,
      "y": 1
    }, {
      "image": "ground-1",
      "x": 15,
      "y": 1
    }, {
      "image": "ground-1",
      "x": 16,
      "y": 1
    }, {
      "image": "ground-1",
      "x": 17,
      "y": 1
    }, {
      "image": "ground-1",
      "x": 18,
      "y": 1
    }, {
      "image": "ground-1",
      "x": 19,
      "y": 1
    }, {
      "image": "ground-1",
      "x": 1,
      "y": 3
    }, {
      "image": "ground-1",
      "x": 2,
      "y": 3
    }, {
      "image": "ground-1",
      "x": 3,
      "y": 3
    }, {
      "image": "ground-1",
      "x": 6,
      "y": 3
    }, {
      "image": "ground-1",
      "x": 7,
      "y": 3
    }, {
      "image": "ground-1",
      "x": 8,
      "y": 3
    }, {
      "image": "ground-1",
      "x": 9,
      "y": 3
    }, {
      "image": "ground-1",
      "x": 10,
      "y": 3
    }, {
      "image": "ground-1",
      "x": 11,
      "y": 3
    }, {
      "image": "ground-1",
      "x": 12,
      "y": 3
    }, {
      "image": "ground-1",
      "x": 13,
      "y": 3
    }, {
      "image": "ground-1",
      "x": 16,
      "y": 3
    }, {
      "image": "ground-1",
      "x": 17,
      "y": 3
    }, {
      "image": "ground-1",
      "x": 0,
      "y": 5
    }, {
      "image": "ground-1",
      "x": 1,
      "y": 5
    }, {
      "image": "ground-2",
      "x": 6,
      "y": 4
    }, {
      "image": "ground-2",
      "x": 13,
      "y": 4
    }, {
      "image": "ground-1",
      "x": 4,
      "y": 7
    }, {
      "image": "ground-1",
      "x": 5,
      "y": 7
    }, {
      "image": "ground-1",
      "x": 6,
      "y": 7
    }, {
      "image": "ground-1",
      "x": 7,
      "y": 7
    }, {
      "image": "ground-1",
      "x": 8,
      "y": 7
    }, {
      "image": "ground-1",
      "x": 11,
      "y": 7
    }, {
      "image": "ground-1",
      "x": 12,
      "y": 7
    }, {
      "image": "ground-1",
      "x": 13,
      "y": 7
    }, {
      "image": "ground-1",
      "x": 14,
      "y": 7
    }, {
      "image": "ground-1",
      "x": 15,
      "y": 7
    }, {
      "image": "ground-1",
      "x": 16,
      "y": 7
    }, {
      "image": "ground-1",
      "x": 17,
      "y": 7
    }, {
      "image": "ground-1",
      "x": 0,
      "y": 8
    }, {
      "image": "ground-1",
      "x": 1,
      "y": 8
    }, {
      "image": "ground-1",
      "x": 2,
      "y": 8
    }, {
      "image": "ground-1",
      "x": 3,
      "y": 8
    }, {
      "image": "ground-2",
      "x": 0,
      "y": 9
    }, {
      "image": "ground-2",
      "x": 1,
      "y": 9
    }, {
      "image": "ground-2",
      "x": 2,
      "y": 9
    }, {
      "image": "ground-2",
      "x": 3,
      "y": 9
    }, {
      "image": "ground-2",
      "x": 0,
      "y": 10
    }, {
      "image": "ground-2",
      "x": 1,
      "y": 10
    }, {
      "image": "ground-2",
      "x": 2,
      "y": 10
    }, {
      "image": "ground-2",
      "x": 3,
      "y": 10
    }, {
      "image": "ground-1",
      "x": 10,
      "y": 10
    }, {
      "image": "ground-1",
      "x": 11,
      "y": 10
    }, {
      "image": "ground-1",
      "x": 12,
      "y": 10
    }, {
      "image": "ground-1",
      "x": 13,
      "y": 10
    }, {
      "image": "ground-1",
      "x": 15,
      "y": 10
    }, {
      "image": "ground-1",
      "x": 16,
      "y": 10
    }, {
      "image": "ground-1",
      "x": 17,
      "y": 12
    }, {
      "image": "ground-1",
      "x": 18,
      "y": 10
    }, {
      "image": "ground-1",
      "x": 19,
      "y": 10
    }, {
      "image": "ground-1",
      "x": 10,
      "y": 12
    }, {
      "image": "ground-1",
      "x": 15,
      "y": 12
    }, {
      "image": "ground-1",
      "x": 16,
      "y": 12
    }, {
      "image": "ground-1",
      "x": 5,
      "y": 15
    }, {
      "image": "ground-1",
      "x": 6,
      "y": 15
    }, {
      "image": "ground-1",
      "x": 7,
      "y": 15
    }, {
      "image": "ground-1",
      "x": 8,
      "y": 15
    }, {
      "image": "ground-1",
      "x": 9,
      "y": 15
    }, {
      "image": "ground-1",
      "x": 0,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 1,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 2,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 3,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 4,
      "y": 16
    }, {
      "image": "ground-2",
      "x": 5,
      "y": 16
    }, {
      "image": "ground-2",
      "x": 6,
      "y": 16
    }, {
      "image": "ground-2",
      "x": 7,
      "y": 16
    }, {
      "image": "ground-2",
      "x": 8,
      "y": 16
    }, {
      "image": "ground-2",
      "x": 9,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 10,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 11,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 12,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 13,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 14,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 15,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 16,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 17,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 18,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 19,
      "y": 16
    }, {
      "image": "ground-1",
      "x": 20,
      "y": 16
    }],
    "ladders": [{
      "x": 20,
      "y": 1
    }, {
      "x": 20,
      "y": 2
    }, {
      "x": 20,
      "y": 3
    }, {
      "x": 20,
      "y": 4
    }, {
      "x": 20,
      "y": 5
    }, {
      "x": 20,
      "y": 6
    }, {
      "x": 20,
      "y": 7
    }, {
      "x": 20,
      "y": 8
    }, {
      "x": 20,
      "y": 9
    }, {
      "x": 20,
      "y": 10
    }, {
      "x": 15,
      "y": 3
    }, {
      "x": 15,
      "y": 4
    }, {
      "x": 15,
      "y": 5
    }, {
      "x": 15,
      "y": 6
    }, {
      "x": 4,
      "y": 3
    }, {
      "x": 4,
      "y": 4
    }, {
      "x": 4,
      "y": 5
    }, {
      "x": 4,
      "y": 6
    }, {
      "x": 17,
      "y": 10
    }, {
      "x": 17,
      "y": 11
    }, {
      "x": 17,
      "y": 12
    }, {
      "x": 9,
      "y": 10
    }, {
      "x": 9,
      "y": 11
    }, {
      "x": 9,
      "y": 12
    }, {
      "x": 9,
      "y": 13
    }, {
      "x": 9,
      "y": 14
    }, {
      "x": 14,
      "y": 12
    }, {
      "x": 14,
      "y": 13
    }, {
      "x": 14,
      "y": 14
    }, {
      "x": 14,
      "y": 15
    }],
    "carrots": [{
      "x": 13,
      "y": 1
    }, {
      "x": 17,
      "y": 2
    }, {
      "x": 3,
      "y": 2
    }, {
      "x": 2,
      "y": 2
    }, {
      "x": 1,
      "y": 2
    }, {
      "x": 8,
      "y": 4
    }, {
      "x": 1,
      "y": 4
    }, {
      "x": 8,
      "y": 6
    }, {
      "x": 7,
      "y": 6
    }, {
      "x": 6,
      "y": 6
    }, {
      "x": 5,
      "y": 6
    }, {
      "x": 17,
      "y": 6
    }, {
      "x": 0,
      "y": 7
    }, {
      "x": 18,
      "y": 9
    }, {
      "x": 14,
      "y": 10
    }, {
      "x": 16,
      "y": 11
    }, {
      "x": 10,
      "y": 11
    }, {
      "x": 2,
      "y": 12
    }, {
      "x": 5,
      "y": 14
    }, {
      "x": 20,
      "y": 15
    }, {
      "x": 10,
      "y": 15
    }, {
      "x": 4,
      "y": 15
    }, {
      "x": 0,
      "y": 15
    }],
    "foxes": [{
      "x": 17,
      "y": 0,
      "direction": "left"
    }, {
      "x": 13,
      "y": 6,
      "direction": "right"
    }, {
      "x": 12,
      "y": 9,
      "direction": "right"
    }, {
      "x": 7,
      "y": 14,
      "direction": "left"
    }, {
      "x": 16,
      "y": 15,
      "direction": "right"
    }]
  }
]


// {
//   "rabbit": {
//     "x": X,
//     "y": Y
//   },
//   "platforms": [{
//     "x": X,
//     "y": Y
//   }],
//   "ladders": [{
//     "x": X,
//     "y": Y
//   }],
//   "carrots": [{
//     "x": X,
//     "y": Y
//   }],
//   "foxes": [{
//     "x": X,
//     "y": Y
//   }]
// }